name: testing_plugin
on:
  push:
    branches: [ ui ]


jobs:
  unitAndApi:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'unit api')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-UnitAndAPI
      - name: Build with Gradle
        run: |
          gradle wrapper --gradle-version 6.8.1
          chmod +x gradlew
          ./gradlew build -x test
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Run API Tests
        if: always()
        run: ./gradlew apiTest
      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
  ui:
    runs-on: self-hosted
    if: "contains(github.event.head_commit.message, 'ui')"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          gradle wrapper --gradle-version 6.8.1
          chmod +x gradlew
          ./gradlew build -x test
      - name: Run Ui Tests
        run: ./src/uiTest/resources/uiTest.sh
